//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        BaltBetService.Models.User[] GetUsers(int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<BaltBetService.Models.User[]> GetUsersAsync(int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        void Create(BaltBetService.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Create", ReplyAction="http://tempuri.org/IUserService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(BaltBetService.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Delete", ReplyAction="http://tempuri.org/IUserService/DeleteResponse")]
        void Delete(BaltBetService.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Delete", ReplyAction="http://tempuri.org/IUserService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(BaltBetService.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindByName", ReplyAction="http://tempuri.org/IUserService/FindByNameResponse")]
        BaltBetService.Models.User FindByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindByName", ReplyAction="http://tempuri.org/IUserService/FindByNameResponse")]
        System.Threading.Tasks.Task<BaltBetService.Models.User> FindByNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindByUserId", ReplyAction="http://tempuri.org/IUserService/FindByUserIdResponse")]
        BaltBetService.Models.User FindByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindByUserId", ReplyAction="http://tempuri.org/IUserService/FindByUserIdResponse")]
        System.Threading.Tasks.Task<BaltBetService.Models.User> FindByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        void Update(BaltBetService.Models.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Update", ReplyAction="http://tempuri.org/IUserService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(BaltBetService.Models.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Web.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Web.UserServiceReference.IUserService>, Web.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BaltBetService.Models.User[] GetUsers(int pageNumber, int pageSize) {
            return base.Channel.GetUsers(pageNumber, pageSize);
        }
        
        public System.Threading.Tasks.Task<BaltBetService.Models.User[]> GetUsersAsync(int pageNumber, int pageSize) {
            return base.Channel.GetUsersAsync(pageNumber, pageSize);
        }
        
        public void Create(BaltBetService.Models.User user) {
            base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task CreateAsync(BaltBetService.Models.User user) {
            return base.Channel.CreateAsync(user);
        }
        
        public void Delete(BaltBetService.Models.User user) {
            base.Channel.Delete(user);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(BaltBetService.Models.User user) {
            return base.Channel.DeleteAsync(user);
        }
        
        public BaltBetService.Models.User FindByName(string userName) {
            return base.Channel.FindByName(userName);
        }
        
        public System.Threading.Tasks.Task<BaltBetService.Models.User> FindByNameAsync(string userName) {
            return base.Channel.FindByNameAsync(userName);
        }
        
        public BaltBetService.Models.User FindByUserId(int id) {
            return base.Channel.FindByUserId(id);
        }
        
        public System.Threading.Tasks.Task<BaltBetService.Models.User> FindByUserIdAsync(int id) {
            return base.Channel.FindByUserIdAsync(id);
        }
        
        public void Update(BaltBetService.Models.User user) {
            base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(BaltBetService.Models.User user) {
            return base.Channel.UpdateAsync(user);
        }
    }
}
